Using ctid as IV base instead of offset calculation
Percona-Lab/pg_tde pull request #107
Opened 2024-01-25 11:19 UTC by dutow

This commit modifies the ID calculation of normal tuples to just use the alrady exisitng ItemPointer to offset the IV instead of the actual offset addresses, as the ItemPointer doesn't change during moves and also easier to use for replication.

As part of this, the structure of the IV is also changed: instead of using the offset as the base number, and incrementing it sequentially, we now insert the "base" ItemPointer at the high part of the IV, and start the counter at the other end, at the low part of the IV.

This means that we are no longer using AES-CTR, but instead rely on a custom AES based encryption, but this is also required for toast, as with that, we can't rely on the uniqueness of the address in the entire data range.

Old encryption tests are also deleted, as they no longer work with these changes.

2024-01-26 11:09 UTC, codeforall requested changes

2024-01-26 11:09 UTC, codeforall commented on src/encryption/enc_tuple.c
> +	iv_prefix[5] = ip.ip_posid % 256;
We should either create a function or a Macro for calculating the IV prefix. The same calculation is happening in two places. Secondly, Also please add comments explaining the calculation

2024-01-26 11:09 UTC, codeforall commented on src/encryption/enc_tuple.c
> +	// ctid stored in item is incorrect (not set) at this point
PostgreSQL discourages C++ (single-line //) code comments. Please change to the multiline comment format.
Ref: https://www.postgresql.org/docs/current/source-format.html

2024-01-26 11:09 UTC, codeforall commented on src/include/encryption/enc_tuple.h
> -		uint64 write_offset_in_file = (_write_bn * BLCKSZ) + _write_offset_in_page; \
Since the PG_TDE_RE_ENCRYPT_TUPLE_DATA Macro is not required anymore, it needs to be removed along with its invocations from 'src/access/pg_tde_prune.c' file. Currently, this is producing many 'unused variable' warnings on the variables, that were declared just to pass to this macro.

2024-01-26 11:11 UTC, codeforall commented
There is also a tiny typo in the commit message. "alrady"

2024-02-05 07:36 UTC, dutow commented on src/access/pg_tdetoast.c
> +		memcpy(iv_prefix, &valueid, sizeof(Oid));
Done.

2024-02-05 07:36 UTC, dutow commented on src/access/pg_tdetoast.c
> +	char iv_prefix[16] = {0,};
done.

2024-02-05 07:36 UTC, dutow commented on src/encryption/enc_tuple.c
> +	iv_prefix[5] = ip.ip_posid % 256;
done.

2024-02-05 07:36 UTC, dutow commented on src/encryption/enc_tuple.c
> +	// ctid stored in item is incorrect (not set) at this point
done

2024-02-05 07:36 UTC, dutow commented on src/include/encryption/enc_tuple.h
> -		uint64 write_offset_in_file = (_write_bn * BLCKSZ) + _write_offset_in_page; \
done

2024-02-05 11:17 UTC, codeforall approved these changes
Looks good

2024-02-07 11:00 UTC, EngineeredVirus approved these changes
Approving this PR, but the code requires refactoring and addition of a lot of comments. The reason for approval is that refactoring should be dealt with separately.

A couple of issues to mention are:
(1) IV should be typedef
(2) 16 should be replaced with a #define (or use an existing define)
(3) 15 should be replaced with the value defined in (2) - 1.
(4) iv prefix initialisation is inconsistent; {0} and {0, }. To avoid such inconsistencies, we should really have a macro or a function instead.
(5) 256 should instead be defined as well.
(6) IMHO, bitwise mask/ops will be more performant.

2024-02-07 11:28 UTC, merged