Key Map Implementation - Replacing TDE Forks
Percona-Lab/pg_tde pull request #113
Opened 2024-01-30 11:14 UTC by EngineeredVirus

This PR has two commits with one commit including some refactoring, and the other commit includes implementation of the key map architecture. Unfortunately, since most of this code was written back in December, it is very hard to recreate a separate PR for the refactoring part. Therefore, for ease, I've created a separate commit for it.

2024-01-30 18:33 UTC, dutow requested changes
I added some comments.

My main issue is: the master key name handling seems to be completely incorrect.

Generally, we have two names:

* A generic name, `master-key`
* A specific version, `master-key-X`, e.g. `master-key-13`

An entire TDE file always has to be encrypted entirely with the same key version, otherwise we won't be able to decrypt it correctly.

This means that:
* If the TDE file doesn't exists, we have to use the generic name (`master-key`), lookup the latest master key version `master-key-X` using `getLatestKey` / `generateKey`, and then save the name of the specific key it gives us (with the version number) to the file.
* When adding a key to an existing file, we have to lookup the specific master key name stored in the file (`master-key-X`), use `keyringGetKey` to retrieve it, and encrypt the new internal key using that specific master key
* When reading an existing file, similarly we have to use `keyringGetKey` to retrieve the specific version specified in the file

2024-01-30 18:33 UTC, dutow commented on src/encryption/enc_aes.c
> + * Provide a simple interface to decrypt a given key.
The comment specifies one key, but this can return multiple internal keys in one batch.

2024-01-30 18:33 UTC, dutow commented on src/encryption/enc_aes.c
> +	sz = SizeOfRelKeysData(1);
How do we know that rel_key_data only contains one key?

2024-01-30 18:33 UTC, dutow commented on src/encryption/enc_aes.c
> +	memcpy(*p_enc_rel_key_data, rel_key_data, sz);
Inconsistent naming: `key` vs `keys`

2024-01-30 18:33 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	int32 file_version;
Won't endianness be an issue with this?

2024-01-30 18:33 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	pg_tde_write_key_map_entry(newrlocator, &int_key, MasterKeyName);
This is incorrect, `MasterKeyName` is the generic name (`master-key`), not a name with the version included (`master-key-X`)

2024-01-30 18:33 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	keys = pg_tde_get_key_from_file(&rel, MasterKeyName);
Same issue: master key should be versioned, otherwise we can't rotate it.

2024-01-30 18:33 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	master_key_info = getMasterKey(master_key_name, true, true);
And again similar comment: This seems incorrect: it always gets the latest master key, even if the file already exists, and is encrypted with an older key. This here should load the key version specified at the beginning of the file (e.g. master-key-X), and use that for encrypting the new entry. Only if the file doesn't exists yet should it try to load the latest master key based on the generic name.

2024-01-31 14:57 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> +AesEncryptKey(const keyInfo *master_key_info, RelKeysData *rel_key_data, RelKeysData **p_enc_rel_key_data, size_t *enc_key_bytes)
It's essentially our interface to the SSL functions. Hence, I put these two functions here.

2024-02-07 08:00 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	int32 file_version;
What challenge do you see here?

2024-02-07 15:41 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> +#define SET_IV(iv)                                      \
I've removed it in favour of a bigger refactoring of this code.

2024-02-07 15:41 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> + * Provide a simple interface to decrypt a given key.
This will be fixed as we refactor the keyring API code.

2024-02-07 15:42 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> +	sz = SizeOfRelKeysData(1);
This will be fixed as we refactor the keyring API code.

2024-02-07 15:42 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> +	memcpy(*p_enc_rel_key_data, rel_key_data, sz);
This will be fixed as we refactor the keyring API code.

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
>  	XLogInsert(RM_TDERMGR_ID, XLOG_TDE_CREATE_FORK);
`CREATE_FORK` is no longer a valid name, this should besomething else.

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	XLogRegisterData((char *) &int_key, sizeof(InternalKey));
Now we are writing unencrypted internal key to the XLog. Previously it was an encrypted internal key. This should stay encrypted.

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	 * TODO: should DB crash after sending XLog, secondaries would create a fork
TODO no longer valid: we don't create fork files.

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	RelKeysData 	*rel_key_data;
Typo in name, should be `keys`

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +tde_encrypt_rel_key(const keyInfo *master_key_info, RelKeysData *rel_key_data)
Type in name, should be `keys`

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +tde_decrypt_rel_key(const keyInfo *master_key_info, RelKeysData *enc_rel_key_data)
Typo in name, should be `keys`

2024-02-07 18:25 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	*db_path = *db_map_path = *db_keydata_path = 0;
Should be `NULL`

2024-02-07 18:25 UTC, dutow commented on src/encryption/enc_aes.c
> +AesEncryptKey(const keyInfo *master_key_info, RelKeysData *rel_key_data, RelKeysData **p_enc_rel_key_data, size_t *enc_key_bytes)
No, this function already uses the functions defined in `enc_aes.h`. The idea is that `enc_aes` uses OpenSSL directly, and doesn't depend on postgres/pg_tde headers -  see the includes above, it had no entries related to these, before this PR.

Anything that depends on postgres/pg_tde headers is implemented in `enc_tuple.h`.

2024-02-08 13:19 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	int32 file_version;
Agreed.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	keys = pg_tde_get_key_from_file(&rel, MasterKeyName);
Resolved per my understanding.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
>  	XLogInsert(RM_TDERMGR_ID, XLOG_TDE_CREATE_FORK);
Resolved.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	XLogRegisterData((char *) &int_key, sizeof(InternalKey));
Resolved.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	 * TODO: should DB crash after sending XLog, secondaries would create a fork
Resolved.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	RelKeysData 	*rel_key_data;
This should be resolved when we remove the flexible array from the RelKeysData data structure.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +tde_encrypt_rel_key(const keyInfo *master_key_info, RelKeysData *rel_key_data)
This should be resolved when we remove the flexible array from the RelKeysData data structure.

2024-02-14 12:35 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +tde_decrypt_rel_key(const keyInfo *master_key_info, RelKeysData *enc_rel_key_data)
This should be resolved when we remove the flexible array from the RelKeysData data structure.

2024-02-14 12:36 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> +AesEncryptKey(const keyInfo *master_key_info, RelKeysData *rel_key_data, RelKeysData **p_enc_rel_key_data, size_t *enc_key_bytes)
Resolved.

2024-02-14 20:06 UTC, dutow approved these changes

2024-02-15 10:25 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +	pg_tde_write_key_map_entry(newrlocator, enc_rel_key_data, master_key_info);
Better to add a new internal key to the memory cache as well, as there is a big chances that the key will be used (no INSERT) right after the relation creation. This is how it was before and I think it makes sense from the performance perspective

2024-02-15 11:36 UTC, EngineeredVirus commented on src/keyring/keyring_api.c
> +const keyInfo* getMasterKey(const char* internalName, int doGenerateKey, int doRaiseError)
Absolutely. 🤦

2024-02-15 11:37 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	master_key_info = getMasterKey(master_key_name, true, true);
Resolved per my understanding.

2024-02-15 11:38 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	*db_path = *db_map_path = *db_keydata_path = 0;
These aren't pointers, so to indicate that, I prefer 0 instead of NULL.

2024-02-15 11:56 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	*db_path = *db_map_path = *db_keydata_path = 0;
Resolved.

2024-02-15 12:00 UTC, dAdAbird approved these changes

2024-02-19 07:42 UTC, merged