Renamed master key to principal key
Percona-Lab/pg_tde pull request #228
Opened 2024-06-25 17:32 UTC by dutow

This commit contains lots of changes, but it's just a repeated
execution of find <...> -exec sed <...>, so everything should
work as before.

Note: PR also contains changes from the SMGR branch merge, as it is based on that, please only check the latest commit: 9c08d95c9b4d4a6ce79f6a42941f5d7ddaa65aa6

2024-06-26 18:14 UTC, dAdAbird requested changes
I made a couple of comments marking not renamed entities. But there are quite a bit of them.
I think patterns *MasterKey* and *masterKey* were omitted.
Plus there is a variable  `mastere_key_info` (a misspelling and a snake case) in [load_latest_versioned_key_name()](https://github.com/Percona-Lab/pg_tde/pull/228/commits/853a923b695ee7469d18ed84cdbd7c106624ee30#diff-fc8109ce322645740f720cb5a9101e7aef73c26a54354df2abc93d60d5007111R510)  (src/catalog/tde_principal_key.c)

2024-06-26 18:14 UTC, dAdAbird commented on src/catalog/tde_global_catalog.c
>  	TDEMasterKey *masterKey;
The variable name (along with the type)

2024-06-26 18:14 UTC, dAdAbird commented on src/catalog/tde_principal_key.c
>  TdeMasterKeylocalState masterKeyLocalState;
Both the type and variable

2024-06-26 18:28 UTC, dutow commented
@dAdAbird yes, I only searched for master.key, not [mM]aster[k]Key. Fixed now.

2024-06-26 19:02 UTC, dAdAbird requested changes
Found a couple more

2024-06-26 19:02 UTC, dAdAbird commented on src/catalog/tde_principal_key.c
> +load_latest_versioned_key_name(TDEPrincipalKeyInfo *mastere_key_info, GenericKeyring *keyring, bool ensure_new_key)
`mastere_key_info` here and all over the func body + in the function prototype, in `src/include/catalog/tde_principal_key.h`

2024-06-27 10:02 UTC, dAdAbird approved these changes

2024-06-27 11:32 UTC, merged

2024-08-27 13:40 UTC, Adammulla commented
Hello Team, When I try to install and configure TDE I am getting create_principal_key don't exists. 
I checked in documentation principal key used instead of master key earlier it was master key in documentation but now changed to principal key . can you please set this in setup code also?