PG-952: Handle non existent principal key in tde_heap
Percona-Lab/pg_tde pull request #287
Opened 2024-09-18 18:48 UTC by dutow

Previously when the database had no principal key, tde_heap simply igored it and created a table without encryption.

With this change, it reports an error instead.

2024-09-19 09:09 UTC, codeforall requested changes

2024-09-19 09:09 UTC, codeforall commented on src/pg_tde_event_capture.c
> +					(errmsg("failed to retrieve principal key")));
Overall, it looks good. However, the error message should be more descriptive and suggestive. Maybe an error hint should be added as well to let users know how they can solve this issue, like suggesting they create a principal key.

2024-09-19 11:52 UTC, dutow commented on src/pg_tde_event_capture.c
> +					(errmsg("failed to retrieve principal key")));
maybe, I just copied the error message we display for tde_heap_basic

2024-09-23 10:46 UTC, dAdAbird approved these changes

2024-09-30 17:30 UTC, merged